name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bazel_otp_name:
        - "24"
        - "25"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: MOUNT BAZEL CACHE
      uses: actions/cache@v3.0.4
      with:
        path: "/home/runner/repo-cache/"
        key: repo-cache
    - name: CONFIGURE BAZEL
      run: |
        echo "${{ secrets.BUILDBUDDY_CERT }}" > buildbuddy-cert.pem
        echo "${{ secrets.BUILDBUDDY_KEY }}" > buildbuddy-key.pem
        cat << EOF >> user.bazelrc
          build:buildbuddy --tls_client_certificate=buildbuddy-cert.pem
          build:buildbuddy --tls_client_key=buildbuddy-key.pem

          build:buildbuddy --build_metadata=ROLE=CI
          build:buildbuddy --build_metadata=VISIBILITY=PUBLIC
          build:buildbuddy --repository_cache=/home/runner/repo-cache/
          build:buildbuddy --color=yes
          build:buildbuddy --disk_cache=
        EOF

        bazelisk info release
    - name: TEST
      run: |
        bazelisk test //... \
          --config=rbe-${{ matrix.bazel_otp_name }} \
          --verbose_failures
